name: Update Reddit Sentiment

on:
  workflow_dispatch:


on:
  schedule:
    - cron: "0 11 * * *"  # 7:00 AM Eastern Time
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install requests

      - name: Run sentiment updater
        run: python update_reddit_sentiment.py

      - name: Commit updated reddit-sentiment.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add reddit-sentiment.json
          git commit -m "Auto-update Reddit sentiment data" || echo "No changes to commit"
          git push
