name: 🔄 Update Squeeze Radar (Finviz)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'  # Runs at 7 AM ET Mon–Fri

jobs:
  update-radar:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: pip install beautifulsoup4 requests

      - name: 🧠 Generate squeeze-radar.json from Finviz
        run: python scripts/generate_squeeze_json.py

      - name: 💾 Commit and push JSON
        run: |
          git config user.name "marlattmedia"
          git config user.email "actions@github.com"
          git add squeeze-radar.json
          git commit -m "🤖 Finviz data refresh"
          git push
