name: Update Reddit Sentiment

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_reddit_sentiment.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "marlattmedia"
          git config --global user.email "actions@github.com"
          git add reddit-sentiment.json
          git commit -m "Daily reddit sentiment update"
          git push
